### ISSUE TITLE
Override Cell component with material-ui Tooltip wrapper throwing JavaScript warning

### ISSUE THREAD

**Issue by chattling** [material-table-core/core#244]
**Describe the bug**
It is continuation of bug reported in #235.
After upgrade to v3.0.13 of @material-table/core, the Tooltip now works, however JavaScript warning still thrown into the console.

```
Warning: Failed prop type: Invalid prop `forwardedRef` of type `function` supplied to `MTableCell`, expected a single ReactElement.
    at MTableCell (http://localhost:3000/uscctools/static/js/8.chunk.js:892:28)
    at MTableCellRef
    at Tooltip (http://localhost:3000/uscctools/static/js/vendors~main.chunk.js:27522:28)
    at WithStyles(ForwardRef(Tooltip)) (http://localhost:3000/uscctools/static/js/vendors~main.chunk.js:37967:31)
    at MyTableCell (http://localhost:3000/uscctools/static/js/17.chunk.js:4934:30)
    at tr
    at TableRow (http://localhost:3000/uscctools/static/js/1.chunk.js:746:23)
    at WithStyles(ForwardRef(TableRow)) (http://localhost:3000/uscctools/static/js/vendors~main.chunk.js:37967:31)
    at MTableBodyRow (http://localhost:3000/uscctools/static/js/8.chunk.js:4451:21)
    at tbody
    at TableBody (http://localhost:3000/uscctools/static/js/1.chunk.js:242:23)
    at WithStyles(ForwardRef(TableBody)) (http://localhost:3000/uscctools/static/js/vendors~main.chunk.js:37967:31)
    at MTableBody (http://localhost:3000/uscctools/static/js/8.chunk.js:5019:37)
    at table
    at Table (http://localhost:3000/uscctools/static/js/1.chunk.js:55:23)
```

I think it is because as part of MTableCell.propTypes definition the forwardedRef is defined as PropTypes.element. It should also be able to accept a function (callback ref).

**Comment by Domino987** [comment]
This will be fixed with the next release: commit 101d290
