### ISSUE TITLE
Grouping doesn't work all the time (Material-Table MUI Version)

### ISSUE THREAD

**Issue by tasoskn** [material-table-core/core#366]
**Bug description**
I'm using **Material-Table for MUI**.
When I load my **next.js page** that has the table in it, half of the times the grouping doesn't work, that's it, headers are not draggable. **Important:** The state of the grouping does NOT change during the interaction with the page. IF the working state of the grouping changes, that happens only on page refresh, or page revisit

**What i tried with no luck:**
1)I've tested different browsers 
2)I've tested fetching the data async vs hard-coding it
3) I tried removing all custom column renderers.
4)I disabled filtering
5)I tried all available tableLayout types 
6)I removed all column cellstyles

At this point, it just seems that getting a working grouping is dependent on pure luck.

- OS: MacOs
- Browser: Chrome, Safari, Firefox
- Version Material-Table-Core for MUI

**Comment by Domino987** [comment]
Could you create a sandbox and a few to reproduce it? I am not sure how supportive we are regarding nextjs I am afraid

**Comment by tasoskn** [comment]
Hi. After trying various things, i found out that the problem is the react beautiful dnd library.
After i installed the next.js version of the library and changed the relevant imports in material-table-core code in node/modules, problem is gone.

**Comment by Domino987** [comment]
Perfect. Do you know a way to specify the one B's if used with next so this dies not happen again ?

**Comment by tasoskn** [comment]
I'm sorry, i don't think i get your question...

**Comment by Domino987** [comment]
My Autocorrect realty messed that up. I was wondering if we can implement something to check for nextjs and tell the developer to install the correct dnd lib when using next js

**Comment by matthewoestreich** [comment]
@tasoskn is this still an issue for you?

**Comment by AshwinTayson** [comment]
@oze4 Yes this is still an issue. With next-js it throws a bunch of errors. @tasoskn Can you tell us how you solved this exactly?

`next-dev.js?3515:32 Warning: Prop `data-rbd-draggable-context-id` did not match. Server: "7" Client: "1"
    at div
    at Draggable (webpack-internal:///./node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:7885:58)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:235:68)
    at PrivateDraggable (webpack-internal:///./node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:8237:26)
    at PublicDraggable (webpack-internal:///./node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:8247:32)
    at span
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at ButtonBase (webpack-internal:///./node_modules/@mui/material/ButtonBase/ButtonBase.js:111:82)
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at TableSortLabel (webpack-internal:///./node_modules/@mui/material/TableSortLabel/TableSortLabel.js:112:83)
    at th
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at TableCell (webpack-internal:///./node_modules/@mui/material/TableCell/TableCell.js:118:83)
    at tr
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at TableRow (webpack-internal:///./node_modules/@mui/material/TableRow/TableRow.js:79:83)
    at thead
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at TableHead (webpack-internal:///./node_modules/@mui/material/TableHead/TableHead.js:51:82)
    at MTableHeader (webpack-internal:///./node_modules/@material-table/core/dist/components/MTableHeader/index.js:48:30)
    at MTableHeaderRef
    at table
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at Table (webpack-internal:///./node_modules/@mui/material/Table/Table.js:68:82)
    at div
    at div
    at div
    at Droppable (webpack-internal:///./node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:8259:69)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:235:68)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:35:72)
    at ScrollBar (webpack-internal:///./node_modules/@material-table/core/dist/components/MTableScrollbar/index.js:33:21)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at Paper (webpack-internal:///./node_modules/@mui/material/Paper/Paper.js:85:83)
    at Container (webpack-internal:///./node_modules/@material-table/core/dist/components/Container/index.js:19:27)
    at ContainerRef
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:16:20)
    at App (webpack-internal:///./node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:6856:25)
    at ErrorBoundary (webpack-internal:///./node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:119:35)
    at DragDropContext (webpack-internal:///./node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:6985:19)
    at MaterialTable (webpack-internal:///./node_modules/@material-table/core/dist/material-table.js:72:37)
    at Table (webpack-internal:///./node_modules/@material-table/core/dist/index.js:120:36)
    at DataTable (webpack-internal:///./src/components/DataTable/index.tsx:34:25)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:35:72)
    at Home (webpack-internal:///./src/pages/index.tsx:21:70)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:35:72)
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at PrivateRoute (webpack-internal:///./src/layout/PrivateRoute.tsx:50:26)
    at InnerThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:21:70)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:47:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:41:5)
    at CustomThemeProvider (webpack-internal:///./src/styles/theme.tsx:25:26)
    at MyApp (webpack-internal:///./src/pages/_app.tsx:54:27)
    at StyleRegistry (webpack-internal:///./node_modules/styled-jsx/dist/stylesheet-registry.js:231:34)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:90:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:331:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:770:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:891:27) 

See more info here: https://nextjs.org/docs/messages/react-hydration-error`

**Comment by fagom** [comment]
Hi, @Domino987 i did some investigation on the Nextjs support. And as per the code, the grouping is dependent on the options prop ```persistentGroupingsId```, which gets the values from localstorage. Adding the persistentGroupingId gives the below error.

```
Server Error
ReferenceError: localStorage is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
MaterialTable.setDataManagerFields
file:///D:/github/test/mtable-core-test/node_modules/@material-table/core/dist/material-table.js (710:38)
new MaterialTable
file:///D:/github/test/mtable-core-test/node_modules/@material-table/core/dist/material-table.js (641:11)
processChild
file:///D:/github/test/mtable-core-test/node_modules/react-dom/cjs/react-dom-server.node.development.js (3305:14)
resolve
file:///D:/github/test/mtable-core-test/node_modules/react-dom/cjs/react-dom-server.node.development.js (3270:5)
ReactDOMServerRenderer.render
file:///D:/github/test/mtable-core-test/node_modules/react-dom/cjs/react-dom-server.node.development.js (3753:22)
ReactDOMServerRenderer.read
file:///D:/github/test/mtable-core-test/node_modules/react-dom/cjs/react-dom-server.node.development.js (3690:29)
Object.renderToString
file:///D:/github/test/mtable-core-test/node_modules/react-dom/cjs/react-dom-server.node.development.js (4298:27)
Object.renderPage
file:///D:/github/test/mtable-core-test/node_modules/next/dist/server/render.js (751:45)
Object.defaultGetInitialProps
file:///D:/github/test/mtable-core-test/node_modules/next/dist/server/render.js (389:51)
Function.getInitialProps
node_modules\next\dist\pages\_document.js (145:19)
```


As per the discussion, in the below link, the page gets rendered on the server side, where localstorage is not available.
https://github.com/vercel/next.js/discussions/19911

Removing the persistentGroupingsId does render the table, but might create some inconsistency in grouping. I might be way off on this as well 😝

**Comment by Domino987** [comment]
That's a good point. Maybe we should add a check if it is there and only do this if it is present. It should not effect the table otherwise because it's just sorting persistence between reloads. Would you mind creating a PR to check for it?

**Comment by Domino987** [comment]
Will be fixed with the next version.
